{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-app.api.name" . }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.api.service.prometheusPort }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "k3s-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}


