{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-app.mysql.name" . }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "k3s-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
