{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k3s-app.serviceAccountName" . }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k3s-app.fullname" . }}-endpoints-reader
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k3s-app.fullname" . }}-endpoints-reader
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k3s-app.fullname" . }}-endpoints-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "k3s-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
