{{- if .Values.rpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-app.rpc.name" . }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
spec:
  type: {{ .Values.rpc.service.type }}
  ports:
    - port: {{ .Values.rpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.rpc.service.prometheusPort }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "k3s-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
{{- end }}
